object AndroidX {
    const val composeVersion = "1.2.0-alpha08"
    private const val navigationVersion = "2.4.2"

    const val coreKtx = "androidx.core:core-ktx:1.6.0"
    const val composeUi = "androidx.compose.ui:ui:$composeVersion"
    const val composeMaterial = "androidx.compose.material:material:$composeVersion"
    const val composeUiToolingPreview = "androidx.compose.ui:ui-tooling-preview:$composeVersion"
    const val lifecycleRuntime = "androidx.lifecycle:lifecycle-runtime-ktx:2.4.1"
    const val activityCompose = "androidx.activity:activity-compose:1.4.0-alpha01"
    const val testJUnit = "androidx.test.ext:junit:1.1.3"
    const val testEspresso = "androidx.test.espresso:espresso-core:3.4.0"
    const val composeUiTestJUnit = "androidx.compose.ui:ui-test-junit4:$composeVersion"
    const val composeUiTooling = "androidx.compose.ui:ui-tooling:$composeVersion"
    const val navigationCompose = "androidx.navigation:navigation-compose:$navigationVersion"
    const val navigationUiKtx = "androidx.navigation:navigation-ui-ktx:$navigationVersion"
    const val navigationRuntimeKtx = "androidx.navigation:navigation-runtime-ktx:$navigationVersion"
    const val appcompat="androidx.appcompat:appcompat:1.3.1"
    const val material="com.google.android.material:material:1.4.0"
}